### ISSUE TITLE
BOM cost?

### ISSUE THREAD

**Issue by taktoa** [joshtyler/manila-ice#2]
I'm designing a similar board (HX4K + gigabit ethernet PHY) and I'm curious what your BOM cost ended up being? What about total cost per board from JLC (including board, stencil, assembly, etc.)? If my design ends up being more expensive, I'll know I did something wrong :-)

**Comment by joshtyler** [comment]
Hi @taktoa,

You can play around with pricing yourself if you like. You just need the following files:
https://github.com/joshtyler/manila-ice/blob/master/hw/outputs/fab.zip
https://github.com/joshtyler/manila-ice/blob/master/hw/outputs/manila_ice-jlc-bom.csv
https://github.com/joshtyler/manila-ice/blob/master/hw/outputs/manila_ice-jlc-cpl-top.csv

Just drag fab.zip onto the JLC quote form, select SMT assembly, then upload the CSV files when prompted. I've just done a quick check and the assembled board currently costs $100.12 in quantity 5 (without shipping, but with optional ENIG finish), I ordered slightly more PCBs and so paid a slightly lower unit cost.

JLC assemble everything on this board except for the FPGA (which is on the back of the PCB), and the connectors. I think I paid about $5 per FPGA from RS (a UK based distributor). The other connectors were from LCSC. The RJ45 I think was about $2 (it is a bit more expensive than others on the site because it has gigabit magnetics integrated). The PMOD connectors and USB connectors I think were tens of cents each.

You don't need to pay for a stencil explicitly (JLC bake it into the assembly cost) but if you want one shipped to you, then it costs $7.

Btw, if you're thinking of doing gigabit networking on the iCE40 FPGAs, bear in mind that the fabric is fairly slow, getting the ethernet interface working at 125 MHz can be a challenge. I can get a loopback test to meet timing at 125MHz no problem, but as I add more to the design, it becomes harder to meet timing. For example with a picorv32 CPU in there, the ethernet doesn't quite meet timing anymore (even though the ethernet clock domain just has a FIFO, and some discrete logic to drive the MII interface). I'm currently looking at implementing TCP in the FPGA logic, and I'm fairly confident that I will be able to get this to meet timing :smile:

**Comment by taktoa** [comment]
Thanks! Gigabit is fortunately not important for my application, but I figured I'd rather have it and not use it than not have it and want it. My application is actually a microphone array for playing around with ultrasound sonar in air (e.g.: to make a depth camera), and the total data rate there is 72 Mb/s, but if I want to get into higher frequency ultrasound the gigabit would come in handy. My board will also have a microcontroller (leaning towards a RISC-V core, funnily enough) so the FPGA is really just there to route data and do serial-to-parallel / parallel-to-serial conversion; setting up protocols will be done by the microcontroller.
